### ISSUE TITLE
Operation not supported

### ISSUE THREAD

**Issue by SHiftLin** [smherwig/phoenix-fileserver#1]
When I run the fileserver with bd-vericrypt and SGX, it shows Operation not supported

     root@lsh-office:~/src/makemanifest/nextfsserver# ./nextfsserver.manifest.sgx -Z /srv/root.crt /srv/proc.crt /srv/proc.key -b bdvericrypt:/srv/fs.crypt.mt:macpassword:36a5a94937d9db7fce549da46a9f6e9ea01686121592a49923f7169318ddfcbb:encpassword:aes-256-xts /etc/clash /srv/fs.crypt.img
     There are no available TCS pages left for a new thread!
     Please try to increase sgx.thread_num in the manifest.
     The current value is 1
     warn tnt_client_from_config:142 timeserver.rsa_n not in config
     2021/05/16 23:29:50 UTC [info] 1 - block device set to "/srv/fs.crypt.img"
     bdvericrypt_enckey(64 bytes):
     0x0000:  c8 33 01 e5 cc 00 44 57 e8 72 ab c5 cb 32 8d 07 
     0x0010:  2f 86 55 75 b5 ee 1e 20 62 c0 96 b6 ad 27 a1 c5 
     0x0020:  98 b2 8f 25 d2 0b 26 ae 4c 40 54 2c 87 7b d3 ac 
     0x0030:  3c b5 84 f3 ef 49 51 62 ef ca f8 bd c4 b2 97 66 
     [die] nextfs_server_open_block_device:2452 ext4_mount(imagepath='/srv/fs.crypt.img', '/', ro=false) failed: Operation not supported

I used Ubuntu 16.04 LTS. This error only occurs when I use bd-vericrypt, but when I use bd-crypt and bd-std, no error occurs. Any idea about the reason? Thank you very much!

**Comment by smherwig** [comment]
Hi Shihan,

I'm not sure if this is the issue, but, if I remember correctly, one unfortunate aspect of bdvericrypt is that if you run an application with it, then stop the application and the fsserver, and then try to run again, bdvericrypt's internal state (namely, the Merkle tree's current root MAC) is lost.   Thus, when relaunching the application with the old fs.img, the filesystem will appear corrupted to lwext4.  In other words, bdvericrypt suffers from a lack of persistence between restarts.  

When performing multiple evaluations, I would always save a copy of the original, initial, filesystem images, and then re-run with them.

- Stephen

**Comment by SHiftLin** [comment]
Hi Stephen,

Thanks for your reply. I found this error also happens when I was using a new filesystem images.  
But I solved the problem. The reason that I didn't use '-p encpassword' when I generated the images.
I followed the README.md in nginx-eval. The makefs in Graphene-vericrypt does not use '-p encpassword'. 
I will submit a pull request to fix the README.md.

Thanks,
Shihan
